### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by manojgetwealthy** [Phrensoua/mui-phone-number#5]
Getting following issue while using in next's project:

error - ReferenceError: window is not defined
    at r (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:22:15664)
    at a (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:22:15752)
    at e.exports (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:22:18789)
    at Object.<anonymous> (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:22:2038)
    at n (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:1:572)
    at Module.<anonymous> (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:108:24389)
    at n (/Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:1:572)
    at /Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:1:1371
    at /Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:1:1382
    at /Users/manojadams/projects/wealthy/goku/node_modules/mui-phone-number/dist/index.js:1:81 {

**Comment by poisonborz** [comment]
Seemingly the component is not compatible with NextJS

**Comment by poisonborz** [comment]
mui-phone-number seems to be abandoned. Try this instead: https://www.npmjs.com/package/material-ui-phone-number

**Comment by manojgetwealthy** [comment]
Unable to use mui-phone-number as it is not compatible with react 18.

Using react-phone-input-2 instead.
